### ISSUE TITLE
Prompts that the user would give WendyAI

### ISSUE THREAD

**Issue by lilyx13** [ollysamm/project-3#15]

**Comment by KanchanSamrit** [comment]
**Prompts that the user would give WendyAI for- **Workplace Engagement**

"Hello"
"Can you provide the overall workplace engagement score for the employee?"
"What are the key factors influencing workplace engagement for this employee?"
"Which departments or teams have the highest levels of employee engagement?"
"Are there any specific areas where employee engagement is particularly low?"
"How does the employee's engagement score compare to their team or department?"
"Are there any specific areas where the employee's workplace engagement is particularly high or low?"
"What are the main drivers of workplace satisfaction for this employee?"
"Can you provide a breakdown of the employee's workplace engagement scores by different dimensions or factors?"
"Are there any notable trends or changes in the employee's workplace engagement over time?"
"What are the top suggestions or feedback provided by the employee to improve workplace engagement?"
"Based on the report, what actions or initiatives would you recommend to enhance the employee's workplace engagement?"
"How does the employee's workplace engagement compare to benchmark data or industry standards?"

**Comment by KanchanSamrit** [comment]
**Prompts that the user would give WendyAI for- **Burnout**

"What are the common signs and symptoms of employee burnout?"
"How can I identify if an employee is experiencing burnout?"
"Are there any specific departments or roles that seem to have a higher risk of burnout?"
"What are the main causes or factors contributing to employee burnout in our organization?"
"Can you provide insights on the current level of burnout among our employees?"
"What are some strategies or interventions to prevent and address employee burnout?"
"Are there any specific warning signs or indicators that suggest an employee is at risk of burnout?"
"What are the potential consequences of unchecked employee burnout in terms of productivity and well-being?"
"How can we create a supportive work environment that reduces the risk of burnout?"
"Based on the data available, what actions or policies would you recommend to mitigate employee burnout?"

**Comment by KanchanSamrit** [comment]
**Prompts that the user would give WendyAI for- **Leadership**

"Can you analyze the company data to identify the most effective leadership styles within our organization?"
"What insights can be derived from the data regarding the correlation between leadership effectiveness and employee performance?"
"Based on the data, are there any specific leadership behaviors or actions that have a significant impact on employee engagement?"
"Can you identify any trends or patterns in the data that suggest areas where leadership development is needed?"
"What metrics or indicators can be used to evaluate the success of leadership initiatives within our company?"
"Are there any correlations between leadership effectiveness and key business outcomes, such as profitability or customer satisfaction?"
"Can you provide recommendations on how to leverage the data to improve leadership decision-making and performance?"
"Based on the data analysis, are there any gaps or opportunities for leadership development programs or training?"
"How does the data reflect the effectiveness of leadership communication within the organization?"
"What benchmarks or industry standards can be used to compare our company's leadership performance?"

**Comment by KanchanSamrit** [comment]
**Prompts that the user would give WendyAI for- **Job Satisfaction**

"What are the key factors that contribute to employee job satisfaction?"
"Can you provide insights into the overall job satisfaction levels within our organization?"
"What are some effective strategies to increase employee job satisfaction?"
"How does job satisfaction impact employee productivity and retention?"
"Can you analyze the data to identify any trends or patterns related to job satisfaction?"
"What are the common challenges that may negatively affect job satisfaction in the workplace?"
"Are there any specific departments or roles where job satisfaction is particularly high or low?"
"What role does workplace culture play in influencing job satisfaction?"
"How can managers and leaders effectively measure and address job satisfaction among their teams?"
"Based on industry benchmarks, how does our company's job satisfaction compare to others in the same sector?"

**Comment by KanchanSamrit** [comment]
**Prompts that the user would give WendyAI for- **Social Capital**

"Can you analyze our organization's social capital and provide insights on its current state?"
"How does social capital contribute to employee engagement and collaboration?"
"What are the indicators or measures that can be used to assess social capital within an organization?"
"Based on available data, can you identify any patterns or trends related to social capital?"
"What are the factors that positively impact social capital within teams and departments?"
"Are there any specific strategies or initiatives that can be implemented to enhance social capital?"
"How does social capital influence knowledge sharing and innovation within the organization?"
"Can you provide examples of successful organizations that have effectively built and utilized social capital?"
"What are the long-term benefits of investing in social capital for the organization?"

**Comment by lilyx13** [comment]
Please copy paste into Google drive folder.

**Comment by lilyx13** [comment]
@ollysamm and @KanchanSamrit These can be used to redefine and improve user stories.

**Comment by ollysamm** [comment]
A lot of these prompts are requests for recommendations on actions to take in the workplace to deal with employee engagement issues. From our mid-sprint meeting on Monday (which I understand @KanchanSamrit couldn't attend), Chad mentioned that Wendy should not be making recommendations. She is only to provide analytical insights based on the data in Holmetrics. @KanchanSamrit, if you haven't already done so, would recommend that you watch the [recording of the meeting in Google Drive](https://drive.google.com/file/d/1tkZ3iDRV-0wgn42bqw9FML9e9YuetawM).

Given that we now have access to the demo company in the Holmetrics app (see [Microsoft Teams](https://teams.microsoft.com/l/message/19:0aRCVS6eH790LTAAV3CLcnlD-vlZA_QZD2TBXb3rGnA1@thread.tacv2/1686181379695?tenantId=307d051f-45ed-4b5d-9be6-2770447a4d64&groupId=f0f93dbc-4fbd-4642-b0bc-86b9fcecfed0&parentMessageId=1686181379695&teamName=WendyAI&channelName=General&createdTime=1686181379695&allowXTenantAccess=false) for details), I would recommend that we review the filters/functionality and knowledge base (support documents) to create the prompts the user would give Wendy. 

@KanchanSamrit please let us know if you are able to continue working on this. If so, let us know when you expect an initial draft to be completed. I'm also happy to pick this up if need be. 🙂

**Comment by KanchanSamrit** [comment]
I got it that Wendy will not provide prompts. No problem I will rewrite the
prompts that user give to Wendy on required basis.

Thanks & Regards,
Kanchan Samrit

**Comment by KanchanSamrit** [comment]
As per suggestion that Wendy will not provide any recommendation  I have made some changes on promts that user would give to WendyAI-

"Analyze employee engagement survey data and identify the factors that correlate with high levels of workplace engagement. Provide recommendations on initiatives or practices that can be implemented to improve overall employee engagement."

"Examine employee performance data in relation to reported levels of workplace burnout. Identify any trends or patterns that suggest a correlation between workload, work-life balance, or other factors and burnout. Provide insights and recommendations for reducing burnout levels."

"Analyze absenteeism and sick leave data to identify any patterns that could be indicative of employee burnout or disengagement. Provide recommendations on interventions or policies that can address these issues and improve overall workplace well-being."

"Examine employee feedback and sentiment data from internal communication channels (e.g., surveys, employee feedback platforms) to identify common sources of dissatisfaction or frustration. Provide insights on areas of improvement to enhance workplace engagement and reduce burnout."

"Analyze workload distribution data across teams or departments and identify any imbalances that may contribute to burnout. Provide recommendations on workload optimization strategies, such as redistributing tasks or implementing resource allocation practices."

"Examine time-tracking data and identify trends in overtime or extended working hours. Analyze the impact of excessive overtime on employee well-being and productivity. Provide insights and recommendations for managing workload and promoting work-life balance."

"Analyze turnover data and identify any patterns or trends that suggest a link between burnout and employee attrition. Provide recommendations on retention strategies and interventions to address burnout and improve employee satisfaction."

"Examine communication and collaboration data, such as email or chat logs, to understand the frequency and quality of interactions among team members. Identify any communication gaps or issues that may contribute to burnout or disengagement. Provide recommendations for fostering better communication and collaboration."

"Analyze training and development data to assess its impact on employee engagement and burnout levels. Identify any gaps in training programs and provide recommendations for enhancing skill development and career growth opportunities."

"Examine performance review data and feedback from managers to identify any instances of micromanagement or excessive pressure that may contribute to burnout. Provide recommendations for promoting a healthy management style and reducing stress levels among employees."

**Comment by KanchanSamrit** [comment]
Prompts that the user would give WendyAI -

"Provide an overview of employee engagement levels across departments and identify any significant variations. Highlight departments with high engagement levels and those that may require additional attention."

"Analyze the correlation between employee engagement levels and key performance metrics such as productivity, customer satisfaction, and retention. Identify any positive relationships and quantify the impact of engagement on business outcomes."

"Identify the factors that contribute most to employee burnout within the organization. Analyze data related to workload, work-life balance, job satisfaction, and stress levels to pinpoint areas that require intervention."

"Analyze the relationship between employee burnout and absenteeism rates. Identify any patterns or trends that suggest higher burnout leading to increased absenteeism, and quantify the financial impact on the organization."

"Examine the data on work hours and overtime for different teams or departments. Identify any groups consistently working longer hours and assess the potential impact on burnout and overall employee well-being."

"Analyze employee feedback data related to workplace culture, leadership, and communication. Identify themes or sentiments that indicate areas where improvements can be made to enhance employee engagement and reduce burnout."

"Examine data on training and development initiatives and assess their effectiveness in mitigating burnout and increasing employee engagement. Identify specific programs or practices that correlate with higher engagement levels."

"Analyze turnover data and identify any patterns related to burnout. Examine the tenure of employees who leave the organization and identify potential indicators of burnout that may have contributed to their departure."

"Identify the most common sources of workplace stress and burnout based on employee feedback or surveys. Provide insights into specific job roles, tasks, or organizational factors that may require attention to reduce burnout levels."

"Examine the impact of flexible work arrangements or remote work policies on employee engagement and burnout. Analyze data on productivity, satisfaction, and stress levels to determine the effectiveness of these policies."

**Comment by KanchanSamrit** [comment]
Yes I have already uploaded the updated version of prompts in Google drive.
Thanks for letting me know.

Thanks & Regards,
Kanchan Samrit

**Comment by lilyx13** [comment]
Prompts need to be checked in reference to Holmetrics filters.
