### ISSUE TITLE
Wireframing

### ISSUE THREAD

**Issue by jasmitnarula** [ollysamm/project-3#2]
# Context
* Provide a tangible representation of Wendy's layout and structure to visualize the user experience

# Definition
* Basic flows of chatting with Wendy and receiving alerts from her

**Comment by lilyx13** [comment]
Hey, we are going to focus on UI wireframing again more so in the next spring as during sprint 2 we will be getting a lot of user data that will help inform follow up here.

Would you mind dropping images of the wireframes that have been worked on here?

**Comment by KanchanSamrit** [comment]
![wendy2](https://github.com/ollysamm/project-3/assets/126908183/820ab3ea-4a3f-473d-8cce-2fc0588c84cc)
![wendy1](https://github.com/ollysamm/project-3/assets/126908183/6848e76b-4bf5-424b-aada-8445528c1db2)

**Comment by jasmitnarula** [comment]
![Image](https://github.com/ollysamm/project-3/assets/125112157/e6df17d2-ef06-429e-b515-9532639fdcc2)
