### ISSUE TITLE
Collecting information from Holmetrics website to get more details on resources

### ISSUE THREAD

**Issue by lilyx13** [ollysamm/project-3#22]

**Comment by lilyx13** [comment]
This task needs a definition of done.

Please share links to research notes in the issue.

**Comment by KanchanSamrit** [comment]
Affecting factors for employee's outcome-
- Workplace engagement
- Burnout
- Social capital
- Job satisfaction
- Leadership way

**Comment by KanchanSamrit** [comment]
We can create reports for each department and locations for each affecting factors such as-
- Accounting
- Engineering
- Sales
- Marketing
- Human Resource
- Executive

Check out this youtube video on how to clone Open API such as chat Gpt-
(I found this video really helpful but sorry guys this one is in hindi you might need to turn on caption)

-https://youtu.be/OAr6AIvH9VY
